import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import {ReactNode} from "react";
import Control from "@/app/Control";

export const metadata: Metadata = {
  title: "WEB tutorials",
  description: "Generated by LGH",
};



export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {

    const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + 'topics', {next: {revalidate: 0}});
    const topics = await resp.json();

    return (
        <html>
          <body>
          <h1>
              <Link href="/">WEB</Link>
          </h1>
          <ol>
              {topics.map((topic :{id : string, title : string}) => (
                  <li key={topic.id}>
                      <Link href={`/read/${topic.id}`}>{topic.title}</Link>
                  </li>
              ))}
          </ol>
            {children}
          <Control />
          </body>
        </html>
  );
}
