import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import {ReactNode} from "react";

export const metadata: Metadata = {
  title: "WEB tutorials",
  description: "Generated by LGH",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {

    const resp = await fetch('http://localhost:9999/topics');
    const topics = await resp.json();

    return (
    <html>
      <body>
      <h1>
          <Link href="/">WEB</Link>
      </h1>
      <ol>
          {topics.map((topic :{id : string, title : string}) => (
              <li key={topic.id}>
                  <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
          ))}
      </ol>
        {children}
      <ul>
          <li><Link href="/create">Create</Link></li>
          <li><Link href="/update/1">Update</Link></li>
          <li><input type="button" value="delete"/></li>
      </ul>
      </body>
    </html>
  );
}
